### ISSUE TITLE
Pytorch mean operator export error

### ISSUE THREAD

**Issue by AlonAzrael** [onnx/onnx-mxnet#18]
Hi, I am trying to export a pytorch model to mxnet by using onnx-mxnet, and there is a mean operator inside model, which is expected to act like a global average pooling.
Here is the code to reproduce the issue:

``` python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import torch.onnx as torch_onnx

class Model(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3,3), stride=1, padding=0, bias=False)

    def forward(self, inputs):

        x = self.conv(inputs)
        x = x.view(x.size()[0], x.size()[1], -1)
        return torch.mean(x, dim=2)

input_shape = (3, 100, 100)
model_onnx_path = "toy_model.onnx"

model = Model()
model.train(False)

dummy_input = Variable(torch.randn(1, *input_shape))
torch_onnx.export(model, dummy_input, model_onnx_path, verbose=True)

import onnx_mxnet, mxnet
sym, params = onnx_mxnet.import_model(model_onnx_path)
```
which produce the error:
```
Traceback (most recent call last):
  File "issue_onnx_mxnet_reduceMean.py", line 33, in <module>
    sym, params = onnx_mxnet.import_model(model_onnx_path)
  File "/home/aaronyin/anaconda3/lib/python3.6/site-packages/onnx_mxnet/__init__.py", line 35, in import_model
    sym, params = graph.from_onnx(model_proto.graph)
  File "/home/aaronyin/anaconda3/lib/python3.6/site-packages/onnx_mxnet/import_onnx.py", line 116, in from_onnx
    new_op, mx_attr = _convert_operator(op_name, onnx_attr)
  File "/home/aaronyin/anaconda3/lib/python3.6/site-packages/onnx_mxnet/import_onnx.py", line 50, in _convert_operator
    op_name, attrs = convert_map[op_name](attrs)
  File "/home/aaronyin/anaconda3/lib/python3.6/site-packages/onnx_mxnet/common.py", line 102, in __call__
    _tk = self._transforms[k]
TypeError: 'set' object is not subscriptable
```
Not sure whether this is an onnx issue or onnx-mxnet issue.
version: pytorch=0.3, onnx=1.0, onnx-mxnet==0.4
Thanks in advance.

**Comment by AlonAzrael** [comment]
After having a look of the code, I think the problem is that in **import\_helper.py**:
``` python
# defs/reduction
'ReduceMax'     : AttrCvt('max', {'axes', 'axis'}),
'ReduceMin'     : AttrCvt('min', {'axes', 'axis'}),
'ReduceSum'     : AttrCvt('sum', {'axes', 'axis'}),
'ReduceMean'    : AttrCvt('mean', {'axes', 'axis'}),
'ReduceProd'    : AttrCvt('prod', {'axes', 'axis'}),
```
the implmentation here using set declaration, not dict, however, in **common.py**:
``` python
elif k in self._transforms:
    new_name, defaults, transform = self._parse_default(self._transforms[k])
```
here `self._transforms` is a set, and that's why `self._transforms[k]` fail, since it is a set...
Is this implementation on purpose? Because changing declaration to `{'axes': 'axis'}` can fix problem.

**Comment by anirudhacharya** [comment]
Hi Alon, 
I looked at the issue and here are the findings -
1. First there is an error in your code - The call to the super() method in the constructor of the Model class takes in an argument, there is none provided in your code.

I replaced this part
`def __init__(self):
        super().__init__()`
 with this -
`def __init__(self):
        super(Model, self).__init__()`

2. This might not be an onnx_mxnet issue because I tried to export the same model into caffe and that failed too with a similar error - 

> Traceback (most recent call last):
  File "alon.py", line 33, in <module>
    prepared_backend = onnx_caffe2.backend.prepare(model)
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx_caffe2/backend.py", line 439, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 154, in check_model
    check_graph(model.graph)
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 127, in check_graph
    check_node(node)
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 40, in check_node
    'NodeProto of type {} did not pass defs schema check.'.format(str(node.op_type)))
ValueError: NodeProto of type ReduceMean did not pass defs schema 
> check.

This is the export torch to caffe code -

`import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import torch.onnx as torch_onnx

class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3,3), stride=1, padding=0, bias=False)

    def forward(self, inputs):
        x = self.conv(inputs)
        x = x.view(x.size()[0], x.size()[1], -1) 
        return torch.mean(x, dim=2)

input_shape = (3, 100, 100)
model_onnx_path = "toy_model.onnx"

model = Model()
model.train(False)

dummy_input = Variable(torch.randn(1, *input_shape))
torch_onnx.export(model, dummy_input, model_onnx_path, verbose=True)

import onnx
import onnx_caffe2.backend
# Load the ONNX ModelProto object. model is a standard Python protobuf object
model = onnx.load(model_onnx_path)
prepared_backend = onnx_caffe2.backend.prepare(model)`

So this might be an issue with how the model is getting serialized into onnx in the first place. Will keep you posted if there are more updates.

**Comment by anirudhacharya** [comment]
More details and a related ticket - [https://github.com/pytorch/pytorch/issues/5146](https://github.com/pytorch/pytorch/issues/5146)
Waiting for a reply.

**Comment by AlonAzrael** [comment]
Hi, 
thanks for pointing out the `super().__init__()` issue, `super()` is actually a [feature](https://stackoverflow.com/questions/10482953/python-extending-with-using-super-python-3-vs-python-2/10483204) introduced in python3, but you are right about changing code to `super(Model, self).__init__()` for compability.

I check the issue you reported in pytorch, they indeed fix some bugs for pytorch model onnx exporting, but the error here wasn't caused by bugs from pytorch, because after I update symbolic.py as [this fix](https://github.com/pytorch/pytorch/commit/b42f1638351259675edc6aa234c1304a98e2c3ce) suggest, the error still remain the same, both in onnx_mxnet and onnx_caffe2. 
And it should be, since the code update about mean operation in symbolic.py is just:
``` python
def mean(g, self, dim=None, keepdim=None):
+    if dim is None and keepdim is None:
+        return g.op("Mean", self)
    # NB: ONNX's default is different from PyTorch's
    if keepdim is None:
        keepdim = 0
    return g.op("ReduceMean", self, axes_i=[dim], keepdims_i=keepdim)
```
it has zero effect on the toy model created above, it still generates a graph and requires a ReduceMean operation:
```
graph(%1 : Float(1, 3, 100, 100)
      %2 : Float(32, 3, 3, 3)) {
  %4 : Float(1, 32, 98, 98) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%1, %2), uses = [%5.i0];
  %5 : Float(1, 32, 9604) = Reshape[shape=[1, 32, -1]](%4), uses = [%6.i0];
  %6 : Float(1, 32) = ReduceMean[axes=[2], keepdims=0](%5), uses = [%0.i0];
  return (%6);
}
```

So, even if we update onnx/symbolic.py in pytorch source code, we will still get the error.
Changing declaration to {'axes': 'axis'} can fix problem in onnx_mxnet.
As for onnx_caffe2, the error is:
```
Traceback (most recent call last):
  File "issue_onnx_caffe2_reduceMean.py", line 40, in <module>
    prepared_backend = onnx_caffe2.backend.prepare(model)
  File "/home/aaronyin/anaconda3/envs/caffe2_test/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 556, in prepare
    _, predict_net = cls.onnx_graph_to_caffe2_net(model.graph, device=device, opset_version=opset_version)
  File "/home/aaronyin/anaconda3/envs/caffe2_test/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 696, in onnx_graph_to_caffe2_net
    predict_net.op.extend(cls._onnx_node_to_caffe2_op(node, opset_version))
  File "/home/aaronyin/anaconda3/envs/caffe2_test/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 577, in _onnx_node_to_caffe2_op
    ops = translator(OnnxNode(node_def), opset_version)
  File "/home/aaronyin/anaconda3/envs/caffe2_test/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 611, in _common_onnx_node_to_caffe2_op
    "Don't know how to translate op {}".format(onnx_op_type))
ValueError: Don't know how to translate op ReduceMean
```
The problem is from __backend.py__ line 121:
```python
_renamed_operators = {
        'Caffe2ConvTranspose':   'ConvTranspose',
        'GlobalMaxPool':         'MaxPool',
        'GlobalAveragePool':     'AveragePool',
        'Pad':                   'PadImage',
        'Neg':                   'Negative',
        'BatchNormalization':    'SpatialBN',
        'InstanceNormalization': 'InstanceNorm',
        'MatMul':                'BatchMatMul',
        'Upsample':              'ResizeNearest',
        'Equal':                 'EQ',
        # 'ReduceMean':            'ReduceBackMean',
    }
```
`_renamed_operators` should have a element `'ReduceMean':            'ReduceBackMean'` that can mapping ReduceMean operation to ReduceBackMean, as onnx and caffe2 have different names on ReduceMean. This code update can fix onnx_caffe2 importing problem.

**Comment by anirudhacharya** [comment]
I will get the latest torch build, replicate this again and get back with a fix.

**Comment by anirudhacharya** [comment]
This PR - #22 fixes the issue.
